### ISSUE TITLE
Document what track/untrack do

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/wib#11]
It's noted [here](https://github.com/chengsoonong/wib/issues/2) that `wib track` isn't exactly `git add`. Coming from a git background, it's not clear from the README what track and untrack are. Could these be documented?

**Comment by chengsoonong** [comment]
Does the extra sentence clarify it enough?

commit d1dba103cd251391604ac7b052cc987dbc5bc441

**Comment by MatthewJA** [comment]
Yep, I think so.

edit: Actually, not so sure — what happens if a file is "untracked" and I `wib up`? Does it delete it on the server or does the server maintain the old version?

**Comment by chengsoonong** [comment]
wib untrack = git rm --cached

https://git-scm.com/docs/git-rm

Still need to commit. And we do not destroy history. I think for editing history, this is beyond the use case for wib.

**Comment by chengsoonong** [comment]
Resolved in d1dba10
